### ISSUE TITLE
Document H264 usage

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/ustreamer#1]
Let's adapt [these technical details](https://github.com/tiny-pilot/tinypilot/tree/experimental/h264#technical-details) ([permalink](https://github.com/tiny-pilot/tinypilot/tree/f66006e91e8b1e084d664fd0244de0773be7fd05#technical-details)) into the instructions we wished we had when we started. We'll add documentation directed at clients who want to use uStreamer's H264 functionality independent of TinyPilot.

The documentation shouldn't mention nginx, Docker, or TinyPilot, just uStreamer and Janus. We can skip explaining all the compilation steps for Janus.

The documentation should explain how to compile uStreamer and the Janus plugin.

The documentation should explain how to launch uStreamer and Janus so that the Janus uStreamer plugin can read the video stream from uStreamer.

The documentation should include source for a sample HTML page that has a `<video>` element and a button to start and stop the WebRTC stream and simple JavaScript to tie it together.

Let's put it in a file called `doc/h264.md`.

**Comment by jotaen4tinypilot** [comment]
@mtlynch would it make sense to split this one up, so for example that I take care of the FE part and Jason of the server part? I haven’t looked at all into the server setup yet, so it probably would take a while for me to get into it. (Happy to do that anyway, but just wanted to check back with you, regarding efficiency.)

It probably still makes sense then if one person was in charge of rounding it up in the end, and making it read like one homogenous document. So the split would be more about the technical expertise and details, and not in the sense that we would just glue together two independent documents.

**Comment by mtlynch** [comment]
@jotaen4tinypilot - I'm thinking this is going to be 90% the frontend part, so it makes sense for you to lead and get assistance from Jason on parts where you're uncertain.

The only backend part is including the instructions for compiling uStreamer with the Janus plugin, but that's pretty trivial (`make WITH_OMX=1 WITH_JANUS=1`) and then adding the `--h264-*` flags to uStreamer.

You can see what you need to know in these PRs and ping Jason if you need extra details:

https://github.com/tiny-pilot/ansible-role-ustreamer/pull/54/files
https://github.com/tiny-pilot/ansible-role-ustreamer/pull/51/files

**Comment by jotaen4tinypilot** [comment]
Cools, thanks for the context.

Unless this is super urgent, I’d just work on this “on the side”, while continuing to look into the frontend follow-ups. I also think we haven’t 100% understood all the nitty gritty details of the frontend yet, at least I haven’t, so it makes sense to keep learning about it before we write it all together.
